// packages/create-tool/src/templates/react/src/App.tsx
import { useState } from 'react';

/**
 * {{TOOL_NAME}} - Chaotools Tool
 *
 * 在 Chaotools 主站中运行时，可以访问 window.__TOOL_CONTEXT__
 * 来获取工具上下文和 SDK 功能
 */

export default function App() {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');

  const handleProcess = () => {
    // TODO: 实现工具逻辑
    setOutput(`输入: ${input}`);
  };

  return (
    <div style={{ maxWidth: 800, margin: '0 auto' }}>
      <h1 style={{ color: '#00ff9d', marginBottom: 20 }}>
        {{TOOL_NAME}}
      </h1>

      <div style={{
        background: '#0d1526',
        border: '1px solid rgba(0, 255, 157, 0.12)',
        borderRadius: 10,
        padding: 20
      }}>
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          placeholder="输入内容..."
          style={{
            width: '100%',
            minHeight: 150,
            padding: 12,
            background: '#070b12',
            border: '1px solid rgba(0, 255, 157, 0.12)',
            borderRadius: 6,
            color: '#c8d6e5',
            fontSize: 14,
            fontFamily: "'JetBrains Mono', monospace",
            resize: 'vertical',
            marginBottom: 12
          }}
        />

        <button
          onClick={handleProcess}
          style={{
            width: '100%',
            padding: 12,
            background: '#00ff9d',
            color: '#070b12',
            border: 'none',
            borderRadius: 6,
            cursor: 'pointer',
            fontWeight: 600,
            marginBottom: 12
          }}
        >
          处理
        </button>

        <div style={{
          background: '#070b12',
          padding: 12,
          borderRadius: 6,
          fontFamily: "'JetBrains Mono', monospace",
          whiteSpace: 'pre-wrap',
          minHeight: 100
        }}>
          {output || '结果将显示在这里'}
        </div>
      </div>
    </div>
  );
}

// packages/create-tool/src/templates/vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

const input = ref('');
const output = ref('');

const handleProcess = () => {
  // TODO: 实现工具逻辑
  output.value = `输入: ${input.value}`;
};
</script>

<template>
  <div style="max-width: 800px; margin: 0 auto;">
    <h1 style="color: #00ff9d; margin-bottom: 20px;">
      {{TOOL_NAME}}
    </h1>

    <div style="
      background: #0d1526;
      border: 1px solid rgba(0, 255, 157, 0.12);
      border-radius: 10px;
      padding: 20px;
    ">
      <textarea
        v-model="input"
        placeholder="输入内容..."
        style="
          width: 100%;
          min-height: 150px;
          padding: 12px;
          background: #070b12;
          border: 1px solid rgba(0, 255, 157, 0.12);
          border-radius: 6px;
          color: #c8d6e5;
          font-size: 14px;
          font-family: 'JetBrains Mono', monospace;
          resize: vertical;
          margin-bottom: 12px;
        "
      />

      <button
        @click="handleProcess"
        style="
          width: 100%;
          padding: 12px;
          background: #00ff9d;
          color: #070b12;
          border: none;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 600;
          margin-bottom: 12px;
        "
      >
        处理
      </button>

      <div style="
        background: #070b12;
        padding: 12px;
        border-radius: 6px;
        font-family: 'JetBrains Mono', monospace;
        white-space: pre-wrap;
        min-height: 100px;
      ">
        {{ output || '结果将显示在这里' }}
      </div>
    </div>
  </div>
</template>
